# This -*- perl -*- script writes the Makefile for Mac::FileSpec::Unixish
# Time-stamp: "1998-11-29 18:54:33 MST"
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
require 5.004;
use strict;
use ExtUtils::MakeMaker;

WriteMakefile(
    'NAME'	   => 'Mac::FileSpec::Unixish',
    'VERSION_FROM' => 'Unixish.pm', # finds $VERSION
    'dist'         => { COMPRESS => 'gzip -9f', SUFFIX => 'gz', },
);

package MY;

sub libscan
{ # Determine things that should *not* be installed
    my($self, $path) = @_;
    return '' if $path =~ m/~/;
    $path;
}

__END__
